import type { Restaurant, MenuItem } from '@/types';

export const demoRestaurant: Restaurant = {
  id: 'demo-restaurant-1',
  name: "Joe's Pizza",
  cuisine: ['Pizza', 'Italian'],
  rating: 8.7,
  priceRange: '$',
  location: {
    address: '7 Carmine St',
    neighborhood: 'Greenwich Village',
    city: 'New York',
    state: 'NY',
    coordinates: {
      lat: 40.7303,
      lng: -74.0028,
    },
  },
  images: ['https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80'],
  popularDishes: ['Margherita Pizza', 'Pepperoni Pizza', 'Garlic Knots'],
  hours: {
    monday: '10:00 AM - 11:00 PM',
    tuesday: '10:00 AM - 11:00 PM',
    wednesday: '10:00 AM - 11:00 PM',
    thursday: '10:00 AM - 11:00 PM',
    friday: '10:00 AM - 1:00 AM',
    saturday: '10:00 AM - 1:00 AM',
    sunday: '10:00 AM - 11:00 PM',
  },
  tags: ['Pizza', 'Italian', 'Casual', 'Quick Bites'],
  ratingCount: 342,
  acceptsReservations: false,
  category: 'restaurants',
};

export const demoMenuItems: MenuItem[] = [
  // Pizzas (Entrees)
  {
    id: 'menu-1',
    name: 'Classic Margherita',
    description: 'Fresh mozzarella, tomato sauce, basil',
    price: 18,
    category: 'entree',
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80',
    portionSize: 'large',
    tags: ['Pizza', 'Vegetarian', 'Italian'],
    popularity: 95,
    isVegetarian: true,
  },
  {
    id: 'menu-2',
    name: 'Pepperoni Pizza',
    description: 'Classic pepperoni with mozzarella and tomato sauce',
    price: 20,
    category: 'entree',
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&q=80',
    portionSize: 'large',
    tags: ['Pizza', 'Italian'],
    popularity: 98,
  },
  {
    id: 'menu-3',
    name: 'White Pizza',
    description: 'Ricotta, mozzarella, garlic, olive oil',
    price: 19,
    category: 'entree',
    imageUrl: 'https://images.unsplash.com/photo-1571407921715-bde6bd5c4cda?w=400&q=80',
    portionSize: 'large',
    tags: ['Pizza', 'Vegetarian', 'Italian'],
    popularity: 88,
    isVegetarian: true,
  },
  {
    id: 'menu-4',
    name: 'Meat Lovers Pizza',
    description: 'Pepperoni, sausage, bacon, ham',
    price: 24,
    category: 'entree',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80',
    portionSize: 'shareable',
    tags: ['Pizza', 'Italian'],
    popularity: 92,
  },
  {
    id: 'menu-5',
    name: 'Veggie Supreme',
    description: 'Bell peppers, onions, mushrooms, olives, tomatoes',
    price: 21,
    category: 'entree',
    imageUrl: 'https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=400&q=80',
    portionSize: 'large',
    tags: ['Pizza', 'Vegetarian', 'Italian'],
    popularity: 85,
    isVegetarian: true,
  },

  // Appetizers
  {
    id: 'menu-6',
    name: 'Garlic Knots',
    description: 'Fresh-baked knots with garlic butter and parmesan',
    price: 6,
    category: 'appetizer',
    imageUrl: 'https://images.unsplash.com/photo-1553030441-0c84ca98dbb0?w=400&q=80',
    portionSize: 'small',
    tags: ['Vegetarian', 'Bread'],
    popularity: 90,
    isVegetarian: true,
  },
  {
    id: 'menu-7',
    name: 'Mozzarella Sticks',
    description: 'Crispy breaded mozzarella with marinara',
    price: 8,
    category: 'appetizer',
    imageUrl: 'https://images.unsplash.com/photo-1531749668029-2db88e4276c7?w=400&q=80',
    portionSize: 'medium',
    tags: ['Vegetarian', 'Fried'],
    popularity: 88,
    isVegetarian: true,
  },
  {
    id: 'menu-8',
    name: 'Buffalo Wings',
    description: '10 wings tossed in buffalo sauce',
    price: 12,
    category: 'appetizer',
    imageUrl: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=400&q=80',
    portionSize: 'medium',
    tags: ['Spicy', 'Wings'],
    popularity: 93,
    spiceLevel: 3,
  },

  // Sides (Salads)
  {
    id: 'menu-9',
    name: 'Caesar Salad',
    description: 'Romaine, parmesan, croutons, caesar dressing',
    price: 10,
    category: 'side',
    imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&q=80',
    portionSize: 'medium',
    tags: ['Vegetarian', 'Salad'],
    popularity: 75,
    isVegetarian: true,
  },
  {
    id: 'menu-10',
    name: 'House Salad',
    description: 'Mixed greens, tomatoes, cucumbers, italian dressing',
    price: 8,
    category: 'side',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
    portionSize: 'medium',
    tags: ['Vegetarian', 'Vegan', 'Salad'],
    popularity: 70,
    isVegetarian: true,
  },

  // Desserts
  {
    id: 'menu-11',
    name: 'Tiramisu',
    description: 'Classic Italian coffee-flavored dessert',
    price: 7,
    category: 'dessert',
    imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80',
    portionSize: 'small',
    tags: ['Vegetarian', 'Italian', 'Coffee'],
    popularity: 85,
    isVegetarian: true,
  },
  {
    id: 'menu-12',
    name: 'Cannoli',
    description: 'Crispy shell filled with sweet ricotta cream',
    price: 5,
    category: 'dessert',
    imageUrl: 'https://images.unsplash.com/photo-1534940306894-e391e4b0d9cd?w=400&q=80',
    portionSize: 'small',
    tags: ['Vegetarian', 'Italian'],
    popularity: 92,
    isVegetarian: true,
  },
];

// Pre-configured scenarios for the demo
export const demoScenarios = [
  {
    id: 'date-night',
    name: 'Date Night',
    description: '2 people, medium hunger',
    partySize: 2,
    hungerLevel: 'medium' as const,
    icon: '💑',
  },
  {
    id: 'family-dinner',
    name: 'Family Dinner',
    description: '4 people, very hungry',
    partySize: 4,
    hungerLevel: 'very-hungry' as const,
    icon: '👨‍👩‍👧‍👦',
  },
  {
    id: 'quick-bite',
    name: 'Quick Bite',
    description: '1 person, light hunger',
    partySize: 1,
    hungerLevel: 'light' as const,
    icon: '🚶',
  },
  {
    id: 'group-celebration',
    name: 'Group Celebration',
    description: '6 people, very hungry',
    partySize: 6,
    hungerLevel: 'very-hungry' as const,
    icon: '🎉',
  },
];
